-- Dairy DataBase Management System

-- Table Name = 1] Products1
--              2] Customers
--              3] Employees
--              4] Sales
--              5] SalesDetails
--              6] Suppliers
--              7] Inventory
--              8] Animals


-- Table & Their Column Name

-- 1] Products1 = 
--              ProductID
--              ProductName
--              Category
--              Price
--              QuantityInStock

CREATE TABLE PRODUCTS1(
  PRODUCTID INT PRIMARY KEY ,
  PRODUCTNAME VARCHAR(100) NOT NULL,
  CATEGORY VARCHAR(50),
  PRICE DECIMAL(10,2) NOT NULL,
  QUANTITYINSTOCK INT NOT NULL
);  

CREATE SEQUENCE  S1
INCREMENT BY 1
START WITH 1 
MINVALUE 1
MAXVALUE 50
NOCYCLE 
NOCACHE;


SELECT * FROM PRODUCTS1;


INSERT INTO PRODUCTS1  VALUES(S1.NEXTVAL,'MILK','DAIRY',2.50,80);
INSERT INTO PRODUCTS1  VALUES(S1.NEXTVAL,'MILK','DAIRY',3.50,80);



--2] CUSTOMERS1 = 
--              CUSTOMERID
--              CUSTOMERNAME
--              ADDRESS
--              PHONENUMBER
--              EMAIL

CREATE SEQUENCE CUS1
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100
NOCYCLE
NOCACHE;

CREATE TABLE CUSTOMERS1(
  CUSTOMERID INT PRIMARY KEY,
  CUSTOMERNAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(255),
  PHONENUMBER VARCHAR(15),
  EMAIL VARCHAR(100)
);  

INSERT INTO CUSTOMERS1 VALUES (CUS1.NEXTVAL,'UDAY','DONDWADE',9158090594,'UDAYPARDESHI29102002@GMAIL.COM');  
INSERT INTO CUSTOMERS1 VALUES (CUS1.NEXTVAL,'AKSHAY','JARANDI',9579102806,'AKSHAYPATIL15102002@GMAIL.COM');

SELECT * FROM CUSTOMERS1;

-- 3] EMPLOYEES3 = 
--                EMPLOYEEID
--                EMPLOYEENAME
--                ROLE
--                SALARY
--                HIREDATE

CREATE SEQUENCE EMP3
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100
NOCYCLE
NOCACHE;

CREATE TABLE EMPLOYEES3(
  EMPLOYEEID INT PRIMARY KEY,
  EMPLOYEENAME VARCHAR(100) NOT NULL,
  ROLE VARCHAR(50),
  SALARY DECIMAL(10,2),
  HIREDATE DATE
);  

INSERT INTO EMPLOYEES3 VALUES(EMP3.NEXTVAL,'ROHIT','MANAGER',50000,'25-5-24');
INSERT INTO EMPLOYEES3 VALUES(EMP3.NEXTVAL,'ABHINAV','FARMER',30000,'27-5-24');

SELECT * FROM EMPLOYEES3;

-- 4] SALES = 
--           SALEID
--           SALEDATE
--           CUSTOMERID
--           TOTALAMOUNT

CREATE SEQUENCE SAL1
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100
NOCYCLE
NOCACHE;

CREATE TABLE SALES(
  SALEID INT PRIMARY KEY,
  SALEDATE DATE NOT NULL,
  CUSTOMERID INT,
  TOTALAMOUNT DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS1(CUSTOMERID)
);  

SELECT * FROM SALES;

-- 5] SALESDETAILS =
--                  SALEDETAILID
--                  SALEID
--                  PRODUCTID
--                  QUANTITY
--                  UNITPRICE

CREATE SEQUENCE SALESDET
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100
NOCYCLE
NOCACHE;

CREATE TABLE SALESDETAILS(
  SALEDETAILID INT PRIMARY KEY,
  SALEID INT,
  PRODUCTID INT,
  QUANTITY INT NOT NULL,
  UNITPRICE DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (SALEID) REFERENCES SALES (SALEID),
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS1 (PRODUCTID)
);  

-- 6] SUPPLIERS = 
--               SUPPLIERID
--               SUPPLIERNAME
--               CONTACTINFO

CREATE SEQUENCE SUP
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100
NOCYCLE
NOCACHE;

CREATE TABLE SUPPLIERS(
  SUPPLIERID INT PRIMARY KEY,
  SUPPLIERNAME VARCHAR(100) NOT NULL,
  CONTACTINFO VARCHAR(255)
);  

INSERT INTO SUPPLIERS VALUES(SUP.NEXTVAL,'FEED SUPPLY LTD','WWW.FEED SUPPLY.COM');
INSERT INTO SUPPLIERS VALUES(SUP.NEXTVAL,'HEALTH SUPPLY LTD','WWW.HEALTH SUPPLY.COM');

SELECT * FROM SUPPLIERS;

-- 7] INVENTORY = 
--               INVENTORYID
--               PRODUCTID
--               SUPPLIERID
--               QUANTITY
--               RECEIVEDDATE

CREATE SEQUENCE INVEN
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100
NOCYCLE
NOCACHE;

CREATE TABLE INVENTORY(
  INVENTORYID INT PRIMARY KEY,
  PRODUCTID INT,
  SUPPLIERID INT,
  QUANTITY INT NOT NULL,
  RECEIVEDDATE DATE NOT NULL,
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS1(PRODUCTID),
  FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIERS(SUPPLIERID)
);  

INSERT INTO INVENTORY VALUES (INVEN.NEXTVAL,1,1,100,'20-5-24');
INSERT INTO INVENTORY VALUES (INVEN.NEXTVAL,2,2,50,'25-5-24');

SELECT * FROM INVENTORY;

-- 8] ANIMALS = 
--             ANIMALID
--             TYPE
--             BREED
--             BIRTHDATE
--             MILKPRODUCTIONPERDAY

CREATE SEQUENCE ANI
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100
NOCYCLE
NOCACHE;

CREATE TABLE ANIMALS (
  ANIMALID INT PRIMARY KEY,
  TYPE VARCHAR(50),
  BREED VARCHAR(50),
  BIRTHDATE DATE,
  MILKPRODUCTIONPERDAY DECIMAL(10,2)
);  

INSERT INTO ANIMALS VALUES (ANI.NEXTVAL,'COW','HOLSTEIN','19-3-01',20.5);
INSERT INTO ANIMALS VALUES (ANI.NEXTVAL,'GOAT','ALPINE','22-10-15',3.5);

SELECT * FROM ANIMALS;






SELECT S.SALEID, S.SALEDATE, P.PRODUCTNAME, SD.QUANTITY, SD.UNITPRICE
FROM SALES S JOIN SALESDETAILS SD 
ON S.SALEID = SD.SALEID 
JOIN PRODUCTS1 P 
ON SD.PRODUCTID = P.PRODUCTID
WHERE S.CUSTOMERID = 1;

SELECT * FROM SALES;

SELECT * FROM SALESDETAILS;

SELECT * FROM PRODUCTS1;

SELECT * FROM CUSTOMERS1;

--DROP SEQUENCE SEQUENCE NAME;
--
--DROP TABLE TABLE NAME;